CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type ENUM('PERMANENT', 'TEMPORARY') NOT NULL,
    announcement_type VARCHAR(20) NOT NULL,
    expiry_date DATETIME NULL,
    category VARCHAR(100),
    priority ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT') NOT NULL DEFAULT 'NORMAL',
    target_audience ENUM('ALL', 'HR_ONLY', 'EMPLOYEES_ONLY') NOT NULL DEFAULT 'ALL',
    created_by VARCHAR(100),
    created_by_name VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE announcements ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS announcement_type VARCHAR(20) NOT NULL DEFAULT 'GENERAL';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS expiry_date DATETIME NULL;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS priority ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT') NOT NULL DEFAULT 'NORMAL';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS target_audience ENUM('ALL', 'HR_ONLY', 'EMPLOYEES_ONLY') NOT NULL DEFAULT 'ALL';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_by_name VARCHAR(255);
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS expires_at DATETIME NULL;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE announcements MODIFY COLUMN type ENUM('PERMANENT', 'TEMPORARY') NOT NULL;
